### ISSUE TITLE
Getting Started - Add information on nuget version

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Netduino.Foundation#13]
Visual Studio 2015 uses version 3.4 of the package manager.  This causes some issues when using the nuget packages within Visual Studio.

Add information regarding the installation of 2.6 of the nuget package manager.

**Comment by bryancostanich** [comment]
This is in the getting started guide now. 3.6 is the latest as of writing, and i don't think they're going to backport any of the 4.x versions. :|
