### ISSUE TITLE
Assembly Mismatch for DS323x and Foundation with v0.13 and v.012

### ISSUE THREAD

**Issue by therealjohn** [WildernessLabs/Netduino.Foundation#23]
While trying to use the latest v0.12.564 version of Netduino.Foundation from NuGet with v0.13.563 of Netduino.Foundation.D323x from NuGet I get the following linking error:

```
Link failure: some assembly references cannot be resolved!!
Assembly: MyApp (1.0.6622.39189) needs assembly 'Netduino.Foundation.RTCs.DS323x' (0.13.0.0)
Assembly: Netduino.Foundation.RTCs.DS323x (0.13.0.0) needs assembly 'Netduino.Foundation' (0.11.0.0)
Error: a3000000
```

Notice that the DS323x library want's version 0.11 of Foundation but the NuGet dependency forces it to install version 0.12. If I downgrade, I have a similar problem but with different version numbers (v.0.10). 

To workaround this:
Remove both NuGets. Install version v0.10 of the D323x NuGet and let it include the v0.10 dependency of Foundation. This older version works.

**Comment by NevynUK** [comment]
Fixed with nuget 0.23.699 released 16 Aug 2018.
