### ISSUE TITLE
Link failure: some assembly references cannot be resolved!! 

### ISSUE THREAD

**Issue by claudiosanchez** [WildernessLabs/Netduino.Foundation#49]
After replicating the code from [Netduino Foundation SSD1306 Sample](http://netduino.foundation/Library/Displays/SSD1306/), I am encountering an Error a3000000.

I added a NuGet reference to the following packages:

- [Netduino.Foundation.SSD1306 v.0.7.0](https://www.nuget.org/packages/Netduino.Foundation.SSD1306/0.7.0)
- [Netduino.Foundation.GraphicsLibrary v.0.7.0](https://www.nuget.org/packages/Netduino.Foundation.GraphicsLibrary/0.7.0)

**Both** of these packages depend on Netduino.Foundation (>= 0.7.0)., as one can observe by opening the **_packages.config_** file.

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Netduino.Foundation" version="0.7.0" targetFramework="netmf43" />
  <package id="Netduino.Foundation.GraphicsLibrary" version="0.7.0" targetFramework="netmf43" />
  <package id="Netduino.Foundation.SSD1306" version="0.7.0" targetFramework="netmf43" />
</packages>`

However, I am getting an _**Error a3000000.**_ with the following output. 

I have push the code to a[ public repo](https://github.com/claudiosanchez/tinyLCD)

Program Output
==========================
Found Assembly mscorlib 4.3.1.0
Found Assembly Microsoft.SPOT.Native 4.3.1.0
Found Assembly Microsoft.SPOT.Hardware 4.3.1.0
Found Assembly Microsoft.SPOT.Net 4.3.1.0
Found Assembly Microsoft.SPOT.Net.Security 4.3.1.0
Found Assembly System 4.3.1.0
Found Assembly System.Net.Security 4.3.1.0
Found Assembly Microsoft.SPOT.Hardware.SerialPort 4.3.1.0
Found Assembly Microsoft.SPOT.IO 4.3.1.0
Found Assembly System.IO 4.3.1.0
Found Assembly Microsoft.SPOT.Hardware.PWM 4.3.1.0
Found Assembly Microsoft.SPOT.Hardware.Usb 4.3.1.0
Found Assembly Netduino.IP 1.0.0.0
Found Assembly Netduino.IP.Interop 1.0.0.0
Found Assembly Netduino.IP.LinkLayers.CC3100 1.0.0.0
Found Assembly SecretLabs.NETMF.Diagnostics 4.3.1.0
Found Assembly GoBus 1.5.0.0
Found Assembly SecretLabs.NETMF.Hardware.Netduino 4.3.1.0
Found Assembly Microsoft.SPOT.Hardware.OneWire 4.3.1.0
Found Assembly Netduino.Foundation.Displays.SSD1306 0.7.0.0
Found Assembly Netduino.Foundation 0.7.0.0
Found Assembly Netduino.Foundation.Displays.GraphicsLibrary 0.7.0.0
Found Assembly tinyLCD 1.0.6739.40409
Found Assembly Microsoft.SPOT.TinyCore 4.3.1.0
Adding pe file /Users/claudio/Projects/tinyLCD/packages/Netduino.Foundation.SSD1306.0.7.0/lib/netmf43/le/Netduino.Foundation.Displays.SSD1306.pe to deployment bundle
Adding pe file /Users/claudio/Projects/tinyLCD/packages/Netduino.Foundation.0.7.0/lib/netmf43/le/Netduino.Foundation.pe to deployment bundle
Adding pe file /Users/claudio/Projects/tinyLCD/packages/Netduino.Foundation.GraphicsLibrary.0.7.0/lib/netmf43/le/Netduino.Foundation.Displays.GraphicsLibrary.pe to deployment bundle
Adding pe file /Users/claudio/Projects/tinyLCD/tinyLCD/bin/Release/le/tinyLCD.pe to deployment bundle
Adding pe file /Users/claudio/.local/share/.NETMicroFramework/frameworks/Microsoft .NET Micro Framework/v4.3/Assemblies/le/Microsoft.SPOT.TinyCore.pe to deployment bundle
Attempting deployment...
Deploying assemblies to device
Deploying assemblies for a total size of 107888 bytes
Assemblies successfully deployed to device.
Looking for the debugging target 8881-4096 to connect to (will time out in 60 seconds)...
Device debugging starting...
Restarting interpreter...
Attaching to device...
Found debugger!

Updating information about assemblies on the debugging target.
The debugging target runtime is loading the application assemblies and starting execution.
Updating thread list
The debugger engine is listening to debug events from the debugging target
Create TS.

 Loading start at 8065cac, end 808cd2c

Assembly: mscorlib (4.3.1.0)

Assembly: Microsoft.SPOT.Native (4.3.1.0)

Assembly: Microsoft.SPOT.Hardware (4.3.1.0)

Assembly: Microsoft.SPOT.Net (4.3.1.0)

Assembly: Microsoft.SPOT.Net.Security (4.3.1.0)

Assembly: System (4.3.1.0)

Assembly: System.Net.Security (4.3.1.0)

Assembly: Microsoft.SPOT.Hardware.SerialPort (4.3.1.0)

Assembly: Microsoft.SPOT.IO (4.3.1.0)

Assembly: System.IO (4.3.1.0)

Assembly: Microsoft.SPOT.Hardware.PWM (4.3.1.0)

Assembly: Microsoft.SPOT.Hardware.Usb (4.3.1.0)

Assembly: Netduino.IP (1.0.0.0)

Assembly: Netduino.IP.Interop (1.0.0.0)

Assembly: Netduino.IP.LinkLayers.CC3100 (1.0.0.0)

Assembly: SecretLabs.NETMF.Diagnostics (4.3.1.0)

Assembly: GoBus (1.5.0.0)

Assembly: SecretLabs.NETMF.Hardware.Netduino (4.3.1.0)

Assembly: Microsoft.SPOT.Hardware.OneWire (4.3.1.0)

Loading Deployment Assemblies.

Attaching deployed file.

Assembly: Netduino.Foundation.Displays.SSD1306 (0.7.0.0)

Attaching deployed file.

Assembly: Netduino.Foundation (0.7.0.0)

Attaching deployed file.

Assembly: Netduino.Foundation.Displays.GraphicsLibrary (0.7.0.0)

Attaching deployed file.

Assembly: tinyLCD (1.0.6739.40450)

Attaching deployed file.

Assembly: Microsoft.SPOT.TinyCore (4.3.1.0)

Resolving.

Link failure: some assembly references cannot be resolved!!

Assembly: Netduino.Foundation.Displays.SSD1306 (0.7.0.0) needs assembly 'Netduino.Foundation' (0.7.0.0)

Assembly: Netduino.Foundation (0.7.0.0) needs assembly 'Microsoft.SPOT.TinyCore' (4.3.1.0)

Assembly: Netduino.Foundation.Displays.GraphicsLibrary (0.7.0.0) needs assembly 'Netduino.Foundation' (0.7.0.0)

Assembly: tinyLCD (1.0.6739.40450) needs assembly 'Netduino.Foundation.Displays.SSD1306' (0.7.0.0)

Assembly: tinyLCD (1.0.6739.40450) needs assembly 'Netduino.Foundation.Displays.GraphicsLibrary' (0.7.0.0)

Assembly: tinyLCD (1.0.6739.40450) needs assembly 'Netduino.Foundation' (0.7.0.0)

Assembly: Microsoft.SPOT.TinyCore (4.3.1.0) needs assembly 'Microsoft.SPOT.Graphics' (4.3.1.0)

Error: a3000000

Waiting for debug commands...

**Comment by adrianstevens** [comment]
@claudiosanchez - sorry about that - the SSD1306 package needed to be updated on our end. All fixed.
