### ISSUE TITLE
SoftwareSPI: Bug in phasing

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Netduino.Foundation#78]
There is a problem with the phasing in the SoftwareSPI class.  This has been fixed in the MF repository.

Translate the fix in WriteRead(byte) method from MF to here and test.

**Comment by adrianstevens** [comment]
Great thx @NevynUK  - I'll review and compare. I thought the same thing but wasn't able to get it working so I couldn't confirm.

**Comment by adrianstevens** [comment]
this is fixed - closing
